title: United Kingdom Repository
description: Philosophical and ethical discussions
baseurl: "/Beliefs"
url: ""

# Build settings
markdown: kramdown

# Include and exclude files
include:
  - README.md
  - Argumentation.md
  - ApplyingTheMoralFramework.md
  - ShouldWeTryToChemicalReverseHomosexuality.md
  - FlawedThinking
  - images
  - styles

exclude:
  - .git
  - .github
  - node_modules
  - utils
  - requirements.txt
  - Gemfile
  - Gemfile.lock
  - vendor

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
